### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by PlagueHO** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 171 \[r1\]](https://reviewable.io:443/reviews/powershell/xstorage/59#-KQlwkNfFcWnN_0BEZST:-KQlwkNfFcWnN_0BEZSU:b-2nk1zh) ([raw file](https://github.com/powershell/xstorage/blob/ab3be97654a21cdf6a4940c33b97c520c7bdb0f4/README.md#L171)):*
> ```Markdown
>              DiskNumber = 2
>              DriveLetter = 'J'
> 			 FSLabel = 'Data'
> ```

Any chance you could change these tabs to spaces while you're at it? :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/59)*

**Comment by PlagueHO** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 171 \[r1\]](https://reviewable.io:443/reviews/powershell/xstorage/59#-KQlwkNfFcWnN_0BEZST:-KQm2xOdYFHBNfm29nzE:bfksnl3) ([raw file](https://github.com/powershell/xstorage/blob/ab3be97654a21cdf6a4940c33b97c520c7bdb0f4/README.md#L171)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Any chance you could change these tabs to spaces while you're at it? :smile:
</details>
They're still there :crying_cat_face: - They're on the FSLabel and DependsOn lines.

I use Visual Studio Code and it has a tabs to spaces extension called "TabSpacer" - it can convert all tabs to spaces in a file.

Sorry to be a pain :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/59)*

**Comment by 4c74356b41** [comment]
I hope that does it

**Comment by PlagueHO** [comment]
:lgtm: Thanks for putting up with my OCD :smile:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/59#-:-KQoMhBRF0rXTl_zbOVn:bvfudcv)*

**Comment by 4c74356b41** [comment]
its fine, we all have them.

**Pull request merged**
