### PR TITLE
Added AllocationUnitSize as parameter for xDisk

### PR DESCRIPTION
**Pull request by wictorwilen**

### CODE REVIEW

**Comment by wictorwilen** [comment]
Any update on merging this?

**Comment by KarolKaczmarek** [comment]
@wictorwilen 
Thanks for contribution. You change looks good, can you please add description of your changes to "Unreleased" section in readme.md? 
After that we will be able to merge it.
Thanks

**Comment by wictorwilen** [comment]
Will do as soon as I know what the "Unreleased" section is :-)

**Comment by KarolKaczmarek** [comment]
Take a look here:
https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#lifecycle-of-a-pull-request

**Comment by wictorwilen** [comment]
Thanks!
Done!

**Comment by KarolKaczmarek** [comment]
Thanks!

**Pull request merged**
