### PR TITLE
Partition resize and destructive switch implemented. Fixes #11, #50 and #89

### LINKED ISSUE #11: xDisk resource does not support resizing an existing partition
If you do something like:

```
Configuration Server
{
    Import-DSCResource -Name xWaitforDisk -Module xStorage
    Import-DSCResource -Name xDisk -Module xStorage

    Node "perftest01"
    {
        xWaitforDisk Disk2
        {
            DiskNumber = 1
            RetryIntervalSec = 60
            RetryCount = 10
        }

        xDisk DVolume
        {
            DiskNumber = 1
            DriveLetter = 'D'
            Size = 1GB
        }
    }
}

Server
Start-DscConfiguration -Force -Verbose -Wait -path .\Server
```

followed by

```
Configuration Server
{
    Import-DSCResource -Name xWaitforDisk -Module xStorage
    Import-DSCResource -Name xDisk -Module xStorage

    Node "perftest01"
    {
        xWaitforDisk Disk2
        {
            DiskNumber = 1
            RetryIntervalSec = 60
            RetryCount = 10
        }

        xDisk DVolume
        {
            DiskNumber = 1
            DriveLetter = 'D'
            Size = 10GB
        }
    }
}

Server
Start-DscConfiguration -Force -Verbose -Wait -path .\Server
```

(note that the only difference is the size specified for `DVolume`)

The DSC run will fail:

```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer PERFTEST01 with user sid
S-1-5-21-1778218145-2021600166-3147052739-5183.
VERBOSE: [PERFTEST01]: LCM:  [ Start  Set      ]
VERBOSE: [PERFTEST01]: LCM:  [ Start  Resource ]  [[xWaitForDisk]Disk2]
VERBOSE: [PERFTEST01]: LCM:  [ Start  Test     ]  [[xWaitForDisk]Disk2]
VERBOSE: [PERFTEST01]:                            [[xWaitForDisk]Disk2] Checking for disk '1' ...
VERBOSE: [PERFTEST01]:                            [[xWaitForDisk]Disk2] Found disk 'HP LOGICAL VOLUME SCSI Disk
Device'.
VERBOSE: [PERFTEST01]: LCM:  [ End    Test     ]  [[xWaitForDisk]Disk2]  in 1.6720 seconds.
VERBOSE: [PERFTEST01]: LCM:  [ Skip   Set      ]  [[xWaitForDisk]Disk2]
VERBOSE: [PERFTEST01]: LCM:  [ End    Resource ]  [[xWaitForDisk]Disk2]
VERBOSE: [PERFTEST01]: LCM:  [ Start  Resource ]  [[xDisk]DVolume]
VERBOSE: [PERFTEST01]: LCM:  [ Start  Test     ]  [[xDisk]DVolume]
VERBOSE: [PERFTEST01]:                            [[xDisk]DVolume] Checking if disk number '1' is initialized...
VERBOSE: [PERFTEST01]:                            [[xDisk]DVolume] Drive D size does not match expected value. Current:
 1073741824 Expected: 524288000
VERBOSE: [PERFTEST01]: LCM:  [ End    Test     ]  [[xDisk]DVolume]  in 0.2350 seconds.
VERBOSE: [PERFTEST01]: LCM:  [ Start  Set      ]  [[xDisk]DVolume]
VERBOSE: [PERFTEST01]:                            [[xDisk]DVolume] Checking existing disk partition style...
VERBOSE: [PERFTEST01]:                            [[xDisk]DVolume] Disk number '1' is already configured for 'GPT'
VERBOSE: [PERFTEST01]:                            [[xDisk]DVolume] Creating the partition...
VERBOSE: [PERFTEST01]:                            [[xDisk]DVolume] Formatting the volume...
The requested access path is already in use.
    + CategoryInfo          : InvalidArgument: (StorageWMI:) [], CimException
    + FullyQualifiedErrorId : StorageWMI 42002,New-Partition
    + PSComputerName        : perftest01

VERBOSE: [PERFTEST01]: LCM:  [ End    Set      ]  [[xDisk]DVolume]  in 5.6560 seconds.
The PowerShell DSC resource MSFT_xDisk threw one or more non-terminating errors while running the Set-TargetResource
functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this
channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : perftest01

VERBOSE: [PERFTEST01]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : perftest01

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 8.485 seconds
```

### PR DESCRIPTION
**Pull request by nyanhp**
New parameters AllowDestructive and ClearDisk added. AllowDestructive indicates that potentially destructive changes (partition size change, file system format) are allowed to take place. AllowDestructive together with ClearDisk furthermore indicates that the target disk should be cleared of all data and OEM partitions.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xstorage/90)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @nyanhp - great job and thanks for submitting another great PR! This branch has some merge conflicts as well as it needs the test coverage improved slightly (it has reduced a bit with this PR). Are you able to see if you could get the tests to cover 5 more lines of code? :grin: No worries if you can't.

I'll try and review tonight.

**Comment by nyanhp** [comment]
Hi @PlagueHO , I hope I increased the coverage enough. Thanks for reviewing!

**Comment by PlagueHO** [comment]
Yep @nyanhp - you nailed it :grin: The code coverage report shows +3% improvement. I'll get the review done ASAP (this weekend). Thanks again sir!

**Comment by PlagueHO** [comment]
Truly superb job @nyanhp - only the most minor nitpicks. Seriously, that is some awesome work :grin:

---

Reviewed 4 of 7 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1, line 434 at r3](https://reviewable.io:443/reviews/powershell/xstorage/90#-KmnHcEdo9K2IN_lekvs:-KmnHcEdo9K2IN_lekvt:b-13qz2k) ([raw file](https://github.com/powershell/xstorage/blob/9e5415f02371b191aff38c03bebfcf3385209c9c/Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1#L434)):*
> ```PowerShell
>         if ($assignedPartition.Size -ne $Size)
>         {
>             if ($AllowDestructive -and $FSFormat -eq 'ReFS')
> ```

Just a tiny nitpick:
Could you nest the $FSFormat if block inside the $AllowDestructive if block?

E.g.
```powershell
if ($AllowDestructive)
{
  if ($FSFormat -eq 'ReFS')
  {
  # ...
  }
  else
  {
  # ...
  }
}
```

---

*[Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.schema.mof, line 12 at r3](https://reviewable.io:443/reviews/powershell/xstorage/90#-KmnIaSHZREwJ0bMCnUi:-KmnIaSHZREwJ0bMCnUj:b-h8pzz7) ([raw file](https://github.com/powershell/xstorage/blob/9e5415f02371b191aff38c03bebfcf3385209c9c/Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.schema.mof#L12)):*
> ```
>     [Write, Description("Specifies the allocation unit size to use when formatting the volume.")] Uint32 AllocationUnitSize;
>     [Write, Description("Specifies the file system format of the new volume."), ValueMap{"NTFS","ReFS"}, Values{"NTFS","ReFS"}] String FSFormat;
>     [Write, Description("Specifies if potentially destructive operations may occur")] Boolean AllowDestructive;
> ```

Nitpick. Can you add a full stop at the end of the description?

---

*[Tests/Unit/MSFT_xDisk.Tests.ps1, line 1317 at r3](https://reviewable.io:443/reviews/powershell/xstorage/90#-KmnJf--42ry0QirxMJb:-KmnJf-0zfNToTEzgAv6:b-tqrhww) ([raw file](https://github.com/powershell/xstorage/blob/9e5415f02371b191aff38c03bebfcf3385209c9c/Tests/Unit/MSFT_xDisk.Tests.ps1#L1317)):*
> ```PowerShell
>                 }
> 
>                 It 'the correct mocks were called' {
> ```

All It blocks should start with 'Should' - I know this is some existing text I've got wrong, but would you mind doing a search/replace to replace all ` It 'the correct mocks were called'` with `It 'Should call the correct mocks'`?

---

*[Tests/Unit/MSFT_xDisk.Tests.ps1, line 1480 at r3](https://reviewable.io:443/reviews/powershell/xstorage/90#-KmnKAbXa8PQXvnTcdez:-KmnKAbXa8PQXvnTcdf-:b-14t2xi) ([raw file](https://github.com/powershell/xstorage/blob/9e5415f02371b191aff38c03bebfcf3385209c9c/Tests/Unit/MSFT_xDisk.Tests.ps1#L1480)):*
> ```PowerShell
>                 Mock -CommandName Set-Partition
>                 Mock -CommandName Resize-Partition
>                  Mock  -CommandName Get-PartitionSupportedSize
> ```

Nitpick: remove extra space at beginning of line (sorry :grin:) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/90#-:-KmnKQjQmsY5NwjzWurE:brwtgey)*

**Comment by nyanhp** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1, line 434 at r3](https://reviewable.io:443/reviews/powershell/xstorage/90#-KmnHcEdo9K2IN_lekvs:-KnJ2k_inaEkjq1YumuQ:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/9e5415f02371b191aff38c03bebfcf3385209c9c/Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1#L434)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Just a tiny nitpick:
Could you nest the $FSFormat if block inside the $AllowDestructive if block?

E.g.
```powershell
if ($AllowDestructive)
{
  if ($FSFormat -eq 'ReFS')
  {
  # ...
  }
  else
  {
  # ...
  }
}
```
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.schema.mof, line 12 at r3](https://reviewable.io:443/reviews/powershell/xstorage/90#-KmnIaSHZREwJ0bMCnUi:-KnJ2qR7vy0M_R8xLiYL:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/9e5415f02371b191aff38c03bebfcf3385209c9c/Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.schema.mof#L12)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick. Can you add a full stop at the end of the description?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xDisk.Tests.ps1, line 1317 at r3](https://reviewable.io:443/reviews/powershell/xstorage/90#-KmnJf--42ry0QirxMJb:-KnJwH5g8gIerzaPYNB_:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/9e5415f02371b191aff38c03bebfcf3385209c9c/Tests/Unit/MSFT_xDisk.Tests.ps1#L1317)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

All It blocks should start with 'Should' - I know this is some existing text I've got wrong, but would you mind doing a search/replace to replace all ` It 'the correct mocks were called'` with `It 'Should call the correct mocks'`?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xDisk.Tests.ps1, line 1480 at r3](https://reviewable.io:443/reviews/powershell/xstorage/90#-KmnKAbXa8PQXvnTcdez:-KnJwLKz-Ik_Rti93PM6:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/9e5415f02371b191aff38c03bebfcf3385209c9c/Tests/Unit/MSFT_xDisk.Tests.ps1#L1480)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: remove extra space at beginning of line (sorry :grin:) 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/90)*

**Comment by nyanhp** [comment]
Hi @PlagueHO , thanks for reviewing yet another pull request :) I have incorporated the changes you mentioned.

**Comment by PlagueHO** [comment]
Hi @nyanhp - it is a pleasure to help get these new features in (many people have wanted this). I'll review now, but there seems to be a syntax error in the unit tests for xDisk which is preventing it from running. Any chance you could fix? I'll review now anyway.

**Comment by PlagueHO** [comment]
It is looking great @nyanhp - just need to get the unit tests running and I'll merge.

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/90#-:-KnLk7J_7dlthaR3Jo2s:b-2syvla)*

**Comment by nyanhp** [comment]
I am not sure what happened here to be honest. I executed the tests many times and they were working. God knows what module version was used for that, as it apparently was not the one I was working on, otherwise I would have spotted the missing curly brace.
I will go over it and try to figure out where my working changes went.

**Comment by nyanhp** [comment]
Hi @plagueHO, I am done. Sorry it took so long.

**Comment by PlagueHO** [comment]
@nyanhp - great job! All good!

:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/90#-:-KokWwDXL95LXeYpz5Oj:b-7pwczk)*

**Pull request merged**
