### PR TITLE
MSFT_xDisk.psm1: Replaced Get-WmiObject with Get-CimInstance

### PR DESCRIPTION
**Pull request by tomtorggler**
Get-WmiObject does not work on Nano Server (as of TP4), so Get/Test-TargetResource failed. Replaced it with Get-CimInstance which seems to work just as well.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xstorage/32)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DSCResources/MSFT_xDisk/MSFT_xDisk.psm1, line 27 \[r1\]](https://reviewable.io:443/reviews/powershell/xstorage/32#-KF7ohSog9I82ExUUke-:-KF7ohSog9I82ExUUke0:907799894) ([raw file](https://github.com/powershell/xstorage/blob/ee3d1008e4a607edd2fe8c9f9b28bb38e2020bb6/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1#L27)):*
Please add unit tests for your specific changes.

It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.

Suggestion: Base the tests on the [Unit tests Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/32)*

**Comment by TravisEz13** [comment]
Additional, existing tests failed, please resolve these issues.

**Comment by tomtorggler** [comment]
Travis, thanks for your feedback. Sorry I didn't think about the tests... I believe the test could be fixed by updating the Mocks in MSFT_xDisk.tests.ps1. Currently they Mock Get-WmiObject which no longer serves because Get-CimInstance is called by the Test/Get functions.

**Comment by TravisEz13** [comment]
That sounds like a plan.  

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/32#-:-KFAqGmo9NI2ECiDdqnB:1208251493)*

**Comment by tomtorggler** [comment]
Hi Travis, I've updated both the MSFT_xDisk.psm1 as well as the MSFT_xDisk.Tests.ps1 files. I did add Get-WmiObject again just in case Get-CimInstance would not return a value. I did also update the Mocks to include Get-CimInstance and removed the -verifiable. Let me know what you think. 
Cheers Tom

**Comment by TravisEz13** [comment]
Tom, The CLA tool says you are internal.  Can you ping me Travis Plunk, with your contact info?  Or is the tool incorrect?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/32#-:-KFHEqpuFb4zpGcuAmiM:86031914)*

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[DSCResources/MSFT_xDisk/MSFT_xDisk.psm1, line 27 \[r1\]](https://reviewable.io:443/reviews/powershell/xstorage/32#-KF7ohSog9I82ExUUke-:-KFHFFNd3fOEAHMKIeoP:47404978) ([raw file](https://github.com/powershell/xstorage/blob/ee3d1008e4a607edd2fe8c9f9b28bb38e2020bb6/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1#L27)):*
Need to verify your CLA, leaving this blocked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/32)*

**Pull request merged**
