### PR TITLE
Update examples - 1-xDisk_InitializeDataDisk.ps1

### PR DESCRIPTION
**Pull request by SwarfegaGit**
Minor change to case of letter to make it easier to read

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xstorage/88)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Thank you for submitting this @SwarfegaGit ! I know this is only the most tiny of tweaks to the examples, but we need to make sure we add a line to the # Unreleased section of the Readme.md - are you able to add this?

**Comment by SwarfegaGit** [comment]
Forgive me, I'm still very new to GitHub as I am an ops guy rather than a developer.
I've checked the README.md file but I don't see an # Unrelease section?

**Comment by johlju** [comment]
@SwarfegaGit We are many Ops and Devs here, so you are among friends :smile: You are correct, there is no Unreleased section in README.md. The Unreleased section is in the CHANGELOG.md, and it was this that @PlagueHO wanted you to change. 😄  He went into old habits since it was in README.md a while back, and still is in a other modules. 😉

**Comment by SwarfegaGit** [comment]
@johlju thanks.  I'll get this updated.  
I noticed yesterday though when using this resource that the parameter names have changed so the examples are no longer valid (EG DiskId is now DiskNumber).  Should I create a new pull request to correct this or can I correct these under this request?

**Comment by johlju** [comment]
@SwarfegaGit In regards to the examples. Thanks for find that! Technically you can make the changes in this PR, it is a small change.
But I suggest, to make it more correct, that you first add an issue, then send in another PR saying that it fixes the issue you submitted (add 'Fixes #<number>' in the PR title or PR description). 
Adding an issue makes it possible for the community to discuss the change, if needed.

**Comment by johlju** [comment]
@SwarfegaGit Hmm.. I saw now that it is an example you already are changing in this PR, so I change my suggestion to just do the other changes in this PR as well. 😄

**Comment by johlju** [comment]
If so you can change the PR title to something like "Updating Examples" instead. And change the PR description to include all the example files you have changed (or use the same information you write in the changelog.md)

**Comment by PlagueHO** [comment]
Doh! @SwarfegaGit - @johlju is quite right - it should have been in CHANGELOG.MD - sorry about that. IF you just add the entry to the CHANGELOG.MD and commit it to the same branch it should appear in this PR and I'll get it merged!

**Comment by SwarfegaGit** [comment]
I've been looking this up and down pulling my hair out as I know what I see in the examples are wrong.  It's only until right now I have realised that I am looking at the examples in the dev branch hence it has new examples which of course differ from the 2.9.0.0 release that I am currently using.  I really apologise for my mistake!

**Comment by johlju** [comment]
@SwarfegaGit 3.0.0.0 will be release soon (with breaking changes). Planned release date was yesterday, which didn't happen, so maybe today. :)

**Comment by johlju** [comment]
@SwarfegaGit And no worries. We are glad you tried to help! We didn't realize you were trying to "change back" the breaking change that was added for this release. So sorry about that. :) You are welcome back to help again! 😄

**Comment by PlagueHO** [comment]
Oh LOL! Thanks for submitting the issue/PR either way @SwarfegaGit - it is definitely appreciated!

3.1.0.0 has now been released and the Wiki etc has been updated to match it and everything should now be in line.

**Pull request closed without merging**
