### PR TITLE
Refactored xOpticalDiskDriveLetter to be IsSingleInstance - Fixes #138

### LINKED ISSUE #138: Convert xOpticalDiskDriveLetter to SingleInstance pattern resource
Because xOpticalDiskDriveLetter can only change the disk letter of a single optical drive in a system then it should use the SingleInstance pattern to ensure only a single resource can be used of this type per config.

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR converts the xOpticalDiskDriveLetter resource over to use the IsSingleInstance pattern.

It also refactors some of the code and tests slightly to simplify them and to also meet HQRM and related style guidelines.

**This Pull Request (PR) fixes the following issues:**
- Fixes #138

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@Johlju - would you mind reviewing? Thank you again!

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xstorage/139)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 58 at r1](https://reviewable.io:443/reviews/powershell/xstorage/139#-L29qNDwTnnKJxjw6QTe:-L29qNDwTnnKJxjw6QTf:behfsod) ([raw file](https://github.com/powershell/xstorage/blob/a5a246e064aeb9096bef1b33839646139d40a089/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L58)):*
> ```PowerShell
> 
>     .PARAMETER IsSingleInstance
>     Specifies the resource is a single instance, the value must be 'Yes'.
> ```

Maybe add 'Not used in Get-TargetResource' (even if it is obvious for this kind of resource, it's the guideline). :)
Throughout the *-TargetResource functions.

---

*[Tests/Integration/MSFT_xOpticalDiskDriveLetter.Integration.Tests.ps1, line 82 at r1](https://reviewable.io:443/reviews/powershell/xstorage/139#-L29rdK-1g41pknycyo9:-L29rdK-1g41pknycyoA:b-qmjbya) ([raw file](https://github.com/powershell/xstorage/blob/a5a246e064aeb9096bef1b33839646139d40a089/Tests/Integration/MSFT_xOpticalDiskDriveLetter.Integration.Tests.ps1#L82)):*
> @skipTest

It think it would look better to use `-Skip:$skipTest` (singular) here instead.
If we are using splatting, then `-Name` should be splatted to? 

```
$itParameters = @{
    Name = 'ItDescription'
    Skip = $true
}

Describe -Name 'Something' {
    It @itParameters {
    }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/139)*

**Comment by johlju** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 279 at r1](https://reviewable.io:443/reviews/powershell/xstorage/139#-L29tSJzmc3EqjHPGAT2:-L29tSJzmc3EqjHPGAT3:b2g1htc) ([raw file](https://github.com/powershell/xstorage/blob/a5a246e064aeb9096bef1b33839646139d40a089/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L279)):*
> $result = -not $result

Couldn't we make this less complicated, maybe we could use `$result = $false`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/139)*

**Comment by PlagueHO** [comment]
Hi @johlju - this is taking me a little bit longer than expected because on close examination of the code I'm really not happy with many of the behavior. So I'm basically extending the tests and refactoring this module significantly.

**Comment by PlagueHO** [comment]
It breaks if there are multiple optical disks in the system as well as for various other edge cases (like if the drive is not mounted at all). So I'm going to extend the integration tests to try and cover some more scenarios.

**Comment by PlagueHO** [comment]
I'm closing this PR to continue the discussion in https://github.com/PowerShell/xStorage/issues/140

**Pull request closed without merging**
