### PR TITLE
Add support for DiskIdType Guid in xDisk, xDiskAccessPath and xWaitForDisk - Fixes #104

### LINKED ISSUE #104: xDiskAccessPath - UniqueId format different between server 2012 and 2016
@PlagueHO I hope this one doesn't cause too much work. We've just deployed out first 2016 server in the lab and noticed that UniqueId has a different format between operating systems. I feel terrible because I was the one that initially suggested using UniqueId but it looks like Guid should have been used instead. I had no idea Microsoft changed the formatting between OS versions. Damn!

Have you seen this as well in your 2016 environment? The problem I face now is our CMDB is set to take in a Guid, 32 to 36 characters.

```
[LABSERVER2012]: PS C:\Users\labuser01\Documents> Get-Disk | Select-Object -Last 1 | Select-Object -Property Guid,UniqueId

Guid                                   UniqueId
----                                   --------
{3dec02ec-708e-45df-b6cc-2e644d57f035} 6000C292A946D3A9C79FDC453A6293FF
```

```
[LABSERVER2016]: PS C:\Users\labuser01\Documents> Get-Disk | Select-Object -Last 1 | Select-Object -Property Guid,UniqueId

Guid                                   UniqueId                                                                  
----                                   --------                                                                  
{f84ea0fe-3a78-4462-a1ed-9820d7965a51} SCSI\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\5&1F2A051C&0&000300:LABSERVER2016
```

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR adds support for specifying the disk to work with using the Disk GUID. This is a unique value that is only assigned to the disk once it is initialized (a partition table is created). It will work with either MBR or GPT partition formats.

I've applied auto-formatting on any files I touched.

Tagging @Zuldan

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xstorage/107)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 15 of 19 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[.markdownlint.json, line 4 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEYBN4kj0RuSL9JCJZ:-KpEYBN4kj0RuSL9JCJ_:bwvov2n) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/.markdownlint.json#L4)):*
> ```JSON
>     "default": true,
>     "MD029": {
>         "style": "ordered"
> ```

Should be "one" now.

---

*[CHANGELOG.md, line 15 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEYQ73b_1bVi8OmuV9:-KpEYQ73b_1bVi8OmuVA:bh8yyp) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/CHANGELOG.md#L15)):*
> ```Markdown
> - Added .markdownlint.json file to configure markdown rules to validate.
> - Clean up Badge area in README.MD - See [Issue 110](https://github.com/PowerShell/xStorage/issues/110)
> - Disabled MD013 rule checking to enable badge table.
> ```

Wouldn't it be better to use headers instead to have this enable? See example in xFailoverCluster and xSQLServer.

Ps. I don't like that there is no way to split a table row on several rows. :disappointed: Ds.

---

*[Tests/Integration/MSFT_xWaitForDisk.Integration.Tests.ps1, line 135 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEaJ2bnq5Rdv3PpdwD:-KpEaJ2bnq5Rdv3PpdwE:b-im9si6) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Integration/MSFT_xWaitForDisk.Integration.Tests.ps1#L135)):*
> ```PowerShell
>                         -ConfigurationData $configData
>                     Start-DscConfiguration -Path $TestDrive -ComputerName localhost -Wait -Verbose -Force
>                 } | Should not throw
> ```

`Should Not Throw` (upper S, N and T). All other tests too.

---

*[Tests/TestHelpers/CommonTestHelper.psm1, line 125 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEb-ItaMNVqZ9W32AO:-KpEb-ItaMNVqZ9W32AP:b-yklzn6) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/TestHelpers/CommonTestHelper.psm1#L125)):*
> ```PowerShell
>         # The disk will be initialized with GPT
>         $diskPartScript += @"
> ```

Remove blank row here? If it is needed for the script to work, than make a comment that it is needed.

---

*[Tests/Unit/MSFT_xDisk.Tests.ps1, line 1929 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEc6ipO_G_ggvjfJSt:-KpEc6ipO_G_ggvjfJSu:b-gtnqd0) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Unit/MSFT_xDisk.Tests.ps1#L1929)):*
> ```PowerShell
>                 $script:result = $null
> 
>                 It 'calling test Should Not Throw' {
> ```

`It 'Should not throw an error'` seems better.

---

*[Tests/Unit/MSFT_xDiskAccessPath.Tests.ps1, line 1429 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEcccLxIAeCh01Bbb3:-KpEcccLxIAeCh01Bbb4:b-cxfbnl) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Unit/MSFT_xDiskAccessPath.Tests.ps1#L1429)):*
> ```PowerShell
>                 $script:result = $null
> 
>                 It 'calling test Should Not Throw' {
> ```

Same as previous comment.

---

*[Tests/Unit/MSFT_xWaitForDisk.Tests.ps1, line 121 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEciDESTm47UZ9Nfg1:-KpEciDESTm47UZ9Nfg2:b-cxfbnl) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Unit/MSFT_xWaitForDisk.Tests.ps1#L121)):*
> ```PowerShell
>                 $script:result = $null
> 
>                 It 'Should Not Throw' {
> ```

Same as previous comment.

---

*[Tests/Unit/MSFT_xWaitForDisk.Tests.ps1, line 198 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEcyfnCJaslIjGqbIZ:-KpEcyfnCJaslIjGqbI_:b-1x9bvi) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Unit/MSFT_xWaitForDisk.Tests.ps1#L198)):*
> ```PowerShell
>                     -Verifiable
> 
>                 It 'Should Not Throw' {
> ```

Same as previous comment. There are a lot of these (maybe even more of these in unchanged code?

---

*[Tests/Unit/StorageDsc.Common.Tests.ps1, line 184 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEdH5kEtad3eSCwqQI:-KpEdH5kEtad3eSCwqQJ:bs4htk8) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Unit/StorageDsc.Common.Tests.ps1#L184)):*
> ```PowerShell
>                 }
> 
>                 It 'Should call exepced mocks' {
> ```

Typo (and all others below too)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/107)*

**Comment by PlagueHO** [comment]
Sorry about all the changes here - it is all working towards HQRM on this module as well.

---

Review status: 12 of 26 files reviewed at latest revision, 10 unresolved discussions.

---

*[.markdownlint.json, line 4 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEYBN4kj0RuSL9JCJZ:-KpHJ8rx_pp1ZFjXQMTO:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/.markdownlint.json#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should be "one" now.
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 15 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEYQ73b_1bVi8OmuV9:-KpHJC6j1k1S3LOscdRR:b4o7ekz) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/CHANGELOG.md#L15)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Wouldn't it be better to use headers instead to have this enable? See example in xFailoverCluster and xSQLServer.

Ps. I don't like that there is no way to split a table row on several rows. :disappointed: Ds.
</blockquote></details>

Agreed and done!

---

*[Tests/Integration/MSFT_xWaitForDisk.Integration.Tests.ps1, line 135 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEaJ2bnq5Rdv3PpdwD:-KpHJEmzlekFzT422qXE:b-wxvvfd) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Integration/MSFT_xWaitForDisk.Integration.Tests.ps1#L135)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

`Should Not Throw` (upper S, N and T). All other tests too.
</blockquote></details>

Did a global search/replace and fixed 114 of these (sorry!).

---

*[Tests/TestHelpers/CommonTestHelper.psm1, line 125 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEb-ItaMNVqZ9W32AO:-KpHJhUpTjgrMJNTTUWo:buf0krk) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/TestHelpers/CommonTestHelper.psm1#L125)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Remove blank row here? If it is needed for the script to work, than make a comment that it is needed.
</blockquote></details>

Doh - no that shouldn't be there. Fixed.

---

*[Tests/Unit/MSFT_xDisk.Tests.ps1, line 1929 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEc6ipO_G_ggvjfJSt:-KpHJwRqiIwqcLz_KVUp:b-whnre6) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Unit/MSFT_xDisk.Tests.ps1#L1929)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

`It 'Should not throw an error'` seems better.
</blockquote></details>

Changed to match all the others. 

---

*[Tests/Unit/MSFT_xDiskAccessPath.Tests.ps1, line 1429 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEcccLxIAeCh01Bbb3:-KpHMytlHXY4yuFCnM-4:b-8aptq6) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Unit/MSFT_xDiskAccessPath.Tests.ps1#L1429)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as previous comment.
</blockquote></details>

Done. I also decided to standardize all the other `it` messages to start with 'Should'.

---

*[Tests/Unit/MSFT_xWaitForDisk.Tests.ps1, line 121 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEciDESTm47UZ9Nfg1:-KpHOH1A370PoaocbrXk:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Unit/MSFT_xWaitForDisk.Tests.ps1#L121)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as previous comment.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xWaitForDisk.Tests.ps1, line 198 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEcyfnCJaslIjGqbIZ:-KpHNpH2uDf4V6nH78Xi:b-s1tl9v) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Unit/MSFT_xWaitForDisk.Tests.ps1#L198)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as previous comment. There are a lot of these (maybe even more of these in unchanged code?
</blockquote></details>

I've gone through all tests and changed them all to use the same message:
```
It 'Should not throw an exception'
```

Sorry about the large number of changed files now!

---

*[Tests/Unit/StorageDsc.Common.Tests.ps1, line 184 at r2](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpEdH5kEtad3eSCwqQI:-KpHO7V08B4fs2swKfmf:b-x9oabi) ([raw file](https://github.com/powershell/xstorage/blob/f17806d5cba3416784d075e5f9eea1544ec96419/Tests/Unit/StorageDsc.Common.Tests.ps1#L184)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Typo (and all others below too)
</blockquote></details>

Good catch! Global search replace fixed them all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/107#-:-KpHOBtura1HAORQ_aKp:b-bgqafb)*

**Comment by PlagueHO** [comment]
Thanks for the review @Johlju - should be good to go now!

---

Review status: 12 of 26 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/107#-:-KpHOZA4GUNcIXCZh7hx:bkyhizm)*

**Comment by johlju** [comment]
:lgtm:

Last comment is non-blocker. 

No worries about making large number of changes. For certain style comments I knew that it will result in a global search/replace by you :wink:  I happy you do that so we rid of all all that technical debt. :smile: 

---

Reviewed 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Tests/Unit/MSFT_xDiskAccessPath.Tests.ps1, line 1639 at r1](https://reviewable.io:443/reviews/powershell/xstorage/107#-KpK7zsimO2fWZO-PJyd:-KpK7zsimO2fWZO-PJye:b-heihcz) ([raw file](https://github.com/powershell/xstorage/blob/4c90b79d11abbcfe37f532ae95ef46d002394ca3/Tests/Unit/MSFT_xDiskAccessPath.Tests.ps1#L1639)):*
> ```PowerShell
>                 }
> 
>                 # skipped due to:  https://github.com/PowerShell/xStorage/issues/22
> ```

This issue is closed, should this be skipped still?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/107#-:-KpK8pCNH9i23p6M_-Se:bjlq9fj)*

**Comment by johlju** [comment]
Something happened to the test in AppVeyor. Maybe kick them off again?

**Comment by PlagueHO** [comment]
I thought closing and reopening the PR was supposed to kick the AppVeyor job. Appears not. I'll need to submit a dummy commit :cry:

@johlju - should be good to go. Can you sign off the last file? Thanks sir!

**Comment by johlju** [comment]
Strange, opening and closing has worked every time so far for me. :)

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/107#-:-KpULNuQGqM8YHlH6qgB:bnfp4nl)*

**Comment by johlju** [comment]
:lgtm:

Just a test how Reviewable behaves after all files has been reviewed and one comment LGTM.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/107#-:-KpULdsYgG03mA-YAYzi:b-uzmz17)*

**Comment by johlju** [comment]
Ah. It seems that I should not write LGTM after reviewing the last, file, but after published the last approved file (marking it green). After I published that, then I should type `:LGTM:' and publish that separably, it then writes out; `all files reviewed at latest revision, all discussions resolved, all commit checks successful.`.
You learn every day. :smile:

**Comment by PlagueHO** [comment]
Thanks @johlju - again, as always, I appreciate your work on this! :grin:

**Pull request merged**
