### PR TITLE
Added Documentation and Examples section to README.MD - Fixes #116

### LINKED ISSUE #116: Link Readme.md to Wiki Entries
**Details of the scenario you tried and the problem that is occurring:**
It is not obvious from the README.MD that there is a Wiki containing the full documentation.

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
N/A

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Added Documentation and Examples section to README.MD. Wording mostly copied from SharePointDsc.

**This Pull Request (PR) fixes the following issues:**
Fixes #116

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xstorage/117)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @Johlju - would you mind reviewing if you get a chance?

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 23 at r1](https://reviewable.io:443/reviews/powershell/xstorage/117#-KsU0AqSDGg-WN8nGB-6:-KsU0AqSDGg-WN8nGB-7:b-77kzpb) ([raw file](https://github.com/powershell/xstorage/blob/651f4d2236f027e95fb19c9d1b177ca98bedd8ee/README.md#L23)):*
> en-US

Starting to think that I don'tknow where to find this folder :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/117)*

**Comment by PlagueHO** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 23 at r1](https://reviewable.io:443/reviews/powershell/xstorage/117#-KsU0AqSDGg-WN8nGB-6:-KsVN6pxIkAGzwZXEaRh:bvwaka8) ([raw file](https://github.com/powershell/xstorage/blob/651f4d2236f027e95fb19c9d1b177ca98bedd8ee/README.md#L23)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> en-US

Starting to think that I don'tknow where to find this folder :)
</blockquote></details>

That is correct 😁 This folder gets created by the Autodocumenation code - so only exists in modules installed from the PS Gallery. I've changed the wording to better reflect this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/117)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 23 at r1](https://reviewable.io:443/reviews/powershell/xstorage/117#-KsU0AqSDGg-WN8nGB-6:-KsYjzLKBGpK_LhP2Wok:b-76l10i) ([raw file](https://github.com/powershell/xstorage/blob/651f4d2236f027e95fb19c9d1b177ca98bedd8ee/README.md#L23)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

That is correct 😁 This folder gets created by the Autodocumenation code - so only exists in modules installed from the PS Gallery. I've changed the wording to better reflect this.
</blockquote></details>

This text looks good to me. But when I download version 3.2.0.0 there is no such folder in the resource from PowerShell Gallery either. The README.md is not there either. Maybe a problem with the release pipeline? Non-blocking for this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/117#-:-KsYkbfQZp5WTMnDM0eE:bnfp4nl)*

**Comment by PlagueHO** [comment]
Hopefully should make more sense now that I've removed the paragraph! :)

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 23 at r1](https://reviewable.io:443/reviews/powershell/xstorage/117#-KsU0AqSDGg-WN8nGB-6:-Ksm6oOvdOf-viNq1VVD:b-4n6zeb) ([raw file](https://github.com/powershell/xstorage/blob/651f4d2236f027e95fb19c9d1b177ca98bedd8ee/README.md#L23)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This text looks good to me. But when I download version 3.2.0.0 there is no such folder in the resource from PowerShell Gallery either. The README.md is not there either. Maybe a problem with the release pipeline? Non-blocking for this PR.
</blockquote></details>

I've removed this whole paragraph until I can implement a process to ensure this info is all being copied into the Resource Module during release.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/117#-:-Ksm6rI0-tz2QrURrBQH:b9l7qeg)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/117#-:-KsnC_YieoZHw3tz_Dq2:bnfp4nl)*

**Pull request merged**
