### PR TITLE
Added .github support files - Fixes #112

### LINKED ISSUE #112: Add .GitHub Contributing, Issue Template and Pull Request Template
Add the files:
 - .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
To this repo to improve the amount of information being collected when issues are raised and to provide a checklist for reviewers/contributors when PR's are raised.

We should use the ones from [xFailOverCluster](https://github.com/PowerShell/xFailOverCluster/tree/dev/.github).

### PR DESCRIPTION
**Pull request by PlagueHO**
Copied from xFailOverCluster with adjustments to resource name.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xstorage/113)

### CODE REVIEW

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/113#-:-KqMjooqJZ1uQdTXxt9c:bnfp4nl)*

**Comment by johlju** [comment]
Was to quick!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 5 at r1](https://reviewable.io:443/reviews/powershell/xstorage/113#-KqMkYumMum7dJkDY0bT:-KqMkYumMum7dJkDY0bU:be5dgsj) ([raw file](https://github.com/powershell/xstorage/blob/9423cdb9f82f656e687851cc12c8a10df4ff5077/.github/PULL_REQUEST_TEMPLATE.md#L5)):*
> ```Markdown
> 
> Please prefix the PR title with the resource name, i.e. 'xDisk: My short description'
> If this is a breaking change, then also prefix the PR title with 'BREAKING CHANGE:', i.e. 'BREAKING CHANGE: xDFSNamespaceFolder: My short description'
> ```

Wrong resource name here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/113#-:-KqMk_xbQeni7kQpW-al:b-rbt4rn)*

**Comment by PlagueHO** [comment]
Doh! I kept missing this one! Fixed.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 5 at r1](https://reviewable.io:443/reviews/powershell/xstorage/113#-KqMkYumMum7dJkDY0bT:-KqMqUs2e-hWytWYX2j0:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/9423cdb9f82f656e687851cc12c8a10df4ff5077/.github/PULL_REQUEST_TEMPLATE.md#L5)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Wrong resource name here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/113#-:-KqMqVPxBNTKHjwSyGqK:b-dqg5it)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/113#-:-KqN4TATda9iTQyrPhXW:bnfp4nl)*

**Pull request merged**
