### PR TITLE
Refactored xOpticalDiskDriveLetter to enable multiple optical disk support - Fixes 140

### LINKED ISSUE #140: Refactor xOpticalDiskDrive to resolve edge case issues and support multi disk systems
@johlju, @kewalaka , @timhaintz  - Could I get some input from you guys: The more I look into this resource, the more I'm finding things that may cause confusion in the long run.

It has a limited scope and also fails in one case:
1. Supports only a single optical disk
2. Fails if the drive is not assigned to a letter at all
3. Having an "Ensure" parameter adds complexity that is not required: it would be easier to allow setting DriveLetter to empty string to dismount the drive letter.

I think I could improve this by
1. adding a DiskId parameter that is the resource Key (removes requirement for IsSingleInstance key). This would be the number of the optical disk number you want to set the DriveLetter for. In a single optical disk system this would be just set to a 1 (I can't default because it is a key). **Note: I called this DiskId to match the other resources in this module (so would allow us to use different disk identifier values in future without requiring a breaking change).**
2. Remove the 'Ensure' parameter because it would be easier to just allow DriveLetter to be an empty string for removing the drive letter.

So for a single optical disk drive system:
```powershell
        xOpticalDiskDriveLetter MountOpticalDiskToZ
        {
            DiskId = 1
            DriveLetter = 'Z'
        }
```

For a system with two optical disk drives:
```powershell
        xOpticalDiskDriveLetter RemoveOpticalDisk1DriveLetter
        {
            DiskId = 1
        }
        xOpticalDiskDriveLetter AssignOpticalDisk2DriveLetterZ
        {
            DiskId = 2
            DriveLetter = 'Z'
        }
```

I think we need to address these issues before the next DSC resource kit goes out. I'm happy to make the changes (I've already begun resolving the errors occurring in the edge cases).

So I need to know if anyone has any objections to this pattern? @Johlju - I will probably close #139 without merging.

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR refactors the xOpticalDiskDriveLetter resource to enable it to work on systems with multiple optical disks.

**This Pull Request (PR) fixes the following issues:**
- Fixes #140 
- Makes #138 redundant (will close)

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

Sorry @Johlju - here is the refactored version. I did quite a lot of clean up on it to try and straighten out some of the logic as well as supporting edge cases and other issues.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xstorage/141)

### CODE REVIEW

**Comment by johlju** [comment]
Can you check failing tests? I review this tomorrow. 😄

**Comment by PlagueHO** [comment]
All fixed! Forgot to save a file before committing. Thanks @johlju

**Comment by johlju** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2QhvSnLdX059bhO1zt:-L2QhvSnLdX059bhO1zu:b2qakya) (no related file):*
Maybe add an example for setting multiple optical drives?

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 25 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2QcfCy1fdb3Umq6ELa:-L2QcfCzxiBKpGrKIAP2:bvxcuh9) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L25)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>     This helper function returns the current drive letter assigned
> ```

Text should be indented one more step. Throughout.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 65 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Qf5BvGMricr0md_8M:-L2Qf5BvGMricr0md_8N:b-i6ilf1) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L65)):*
> ```PowerShell
>         [Parameter()]
>         [Switch]
>         $ReturnDeviceIdOnNoDriveLetter
> ```

Minor, Non-blocking: Instead of this parameter, you could maybe returned a hash table with both values  (drive letter or blank, and device ID) each call? One less call to WMI in the Set-TargetResource function. And you could use devide id in verbose and error messages if needed.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 86 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Qe8J2HW9FOqddkYtx:-L2Qe8J3QkiR_HGmiefU:btktu6t) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L86)):*
> $DiskId - 1

Could you add a comment for why we need subtract 1 from disk id?

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 355 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Qgcffvgyo0DWIB8j0:-L2Qgcffvgyo0DWIB8j1:b-8g3let) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L355)):*
> ```PowerShell
>             if ($existingVolume)
>             {
>                 # The desired drive letter is already assigned to another drive - can't proceed
> ```

Shouldn't throw at this point, since it can't set the desired state?

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.schema.mof, line 6 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2QjUQRYMgftRS1xS7B:-L2QjUQRYMgftRS1xS7C:b-xn68rx) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.schema.mof#L6)):*
> ```
> {
>     [Key, Description("Specifies the optical disk number for the disk to assign the drive letter to.")] String DiskId;
>     [Required, Description("Specifies the drive letter to assign to the optical disk. Can be a single letter, optionally followed by a colon.")] String DriveLetter;
> ```

Maybe add that when 'Ensure' is set to 'Absent', this value can be set to anything?

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/README.md, line 1 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2QjMPm5nw6DQrtY4f6:-L2QjMPm5nw6DQrtY4f7:basfzc) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/README.md#L1)):*
> ```Markdown
> # Description
> ```

Maybe add how the user get's the disk id?

---

*[Modules/xStorage/Examples/Resources/xOpticalDiskDriveLetter/1-xOpticalDiskDriveLetter_RemoveDriveLetter.ps1, line 8 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2QhoJag6k1svNeGmB-:-L2QhoJag6k1svNeGmB0:bbwuthj) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/Examples/Resources/xOpticalDiskDriveLetter/1-xOpticalDiskDriveLetter_RemoveDriveLetter.ps1#L8)):*
> ```PowerShell
> Configuration Example
> {
> ```

Remove extra blank row

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/141)*

**Comment by PlagueHO** [comment]
Review status: 6 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2QhvSnLdX059bhO1zt:-L2U0tBGn7dSq77LXqXF:b-bjvex) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe add an example for setting multiple optical drives?
</blockquote></details>

Great review and great comments! All done I think! Thanks @johlju.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 25 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2QcfCy1fdb3Umq6ELa:-L2TtZlAOFoz5R1xxjyq:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L25)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Text should be indented one more step. Throughout.
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 65 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Qf5BvGMricr0md_8M:-L2Tx43KYbmaNuZI1Any:b6ukza6) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L65)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Minor, Non-blocking: Instead of this parameter, you could maybe returned a hash table with both values  (drive letter or blank, and device ID) each call? One less call to WMI in the Set-TargetResource function. And you could use devide id in verbose and error messages if needed.
</blockquote></details>

Great idea! Done.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 86 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Qe8J2HW9FOqddkYtx:-L2TxxhksCV3G3Wgg14l:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L86)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $DiskId - 1

Could you add a comment for why we need subtract 1 from disk id?
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 355 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Qgcffvgyo0DWIB8j0:-L2TyohiZ-N7scJyRwAO:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L355)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Shouldn't throw at this point, since it can't set the desired state?
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.schema.mof, line 6 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2QjUQRYMgftRS1xS7B:-L2TzI4sOPLp4pioQKS5:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.schema.mof#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe add that when 'Ensure' is set to 'Absent', this value can be set to anything?
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/README.md, line 1 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2QjMPm5nw6DQrtY4f6:-L2U-cMrvMCuFs2v6OBr:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/README.md#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe add how the user get's the disk id?
</blockquote></details>

Done.

---

*[Modules/xStorage/Examples/Resources/xOpticalDiskDriveLetter/1-xOpticalDiskDriveLetter_RemoveDriveLetter.ps1, line 8 at r2](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2QhoJag6k1svNeGmB-:-L2U-m3naJaGMZ0aOmkF:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/bbb9ae9784ec9503f0b039a1f9c957d2ad4a2487/Modules/xStorage/Examples/Resources/xOpticalDiskDriveLetter/1-xOpticalDiskDriveLetter_RemoveDriveLetter.ps1#L8)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Remove extra blank row
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/141)*

**Comment by johlju** [comment]
Awesom work! You caught stuff that I missed in the review, and good job on the documentation part, very descriptive texts! :smile: 

Just minor and non-blocking comments.

---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 76 at r3](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Vnaggn6QP6m8vIJZp:-L2Vnaggn6QP6m8vIJZq:bxe361) ([raw file](https://github.com/powershell/xstorage/blob/0f62bc9a5e39f809918989e4fb14437feccf2d16/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L76)):*
> ```PowerShell
>     }
> 
>     $deviceId = ''
> ```

Non-blocking: Why not return `$deviceId = $opticalDisk.Drive` after `Assert-DriveLetterValid` succeeds too? Couldn't it be set on both success and fail of `Assert-DriveLetterValid` instead of setting it to blank here ?

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 117 at r3](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Vo1Dtproxub53YvEV:-L2Vo1Dtproxub53YvEW:b5hnwrg) ([raw file](https://github.com/powershell/xstorage/blob/0f62bc9a5e39f809918989e4fb14437feccf2d16/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L117)):*
> ```PowerShell
>     }
> 
>     $driveInfo = @{
> ```

Non-blocking: Could just return the hash table directly without adding it to a variable first.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/README.md, line 15 at r3](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Vp6ia8ImEYmkuEyhd:-L2Vp6ia8ImEYmkuEyhe:b596wic) ([raw file](https://github.com/powershell/xstorage/blob/0f62bc9a5e39f809918989e4fb14437feccf2d16/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/README.md#L15)):*
> returnedwhen

Typo

---

*[Modules/xStorage/Examples/Resources/xOpticalDiskDriveLetter/3-xOpticalDiskDriveLetter_SetDriveLetterMulti.ps1, line 27 at r3](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2VpW5YEpKFC0c-T-Qf:-L2VpW5YEpKFC0c-T-Qg:b-c0ecx0) ([raw file](https://github.com/powershell/xstorage/blob/0f62bc9a5e39f809918989e4fb14437feccf2d16/Modules/xStorage/Examples/Resources/xOpticalDiskDriveLetter/3-xOpticalDiskDriveLetter_SetDriveLetterMulti.ps1#L27)):*
> Thurd

Typo (funny typo ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/141#-:-L2Vq3T0oEDv8Ytbl4pz:bsjhrup)*

**Comment by PlagueHO** [comment]
All done! Thanks @Johlju

---

Review status: 10 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 76 at r3](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Vnaggn6QP6m8vIJZp:-L2ZBx4XW_-ytbxgd1Ce:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/0f62bc9a5e39f809918989e4fb14437feccf2d16/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L76)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking: Why not return `$deviceId = $opticalDisk.Drive` after `Assert-DriveLetterValid` succeeds too? Couldn't it be set on both success and fail of `Assert-DriveLetterValid` instead of setting it to blank here ?
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1, line 117 at r3](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Vo1Dtproxub53YvEV:-L2ZCHm9c1pOFBC8wqAm:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/0f62bc9a5e39f809918989e4fb14437feccf2d16/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/MSFT_xOpticalDiskDriveLetter.psm1#L117)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking: Could just return the hash table directly without adding it to a variable first.
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/README.md, line 15 at r3](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2Vp6ia8ImEYmkuEyhd:-L2ZCOJnGcJHY9bTa0Sl:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/0f62bc9a5e39f809918989e4fb14437feccf2d16/Modules/xStorage/DSCResources/MSFT_xOpticalDiskDriveLetter/README.md#L15)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> returnedwhen

Typo
</blockquote></details>

Done.

---

*[Modules/xStorage/Examples/Resources/xOpticalDiskDriveLetter/3-xOpticalDiskDriveLetter_SetDriveLetterMulti.ps1, line 27 at r3](https://reviewable.io:443/reviews/powershell/xstorage/141#-L2VpW5YEpKFC0c-T-Qf:-L2ZCPJoC2IR3eZ2aRRM:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/0f62bc9a5e39f809918989e4fb14437feccf2d16/Modules/xStorage/Examples/Resources/xOpticalDiskDriveLetter/3-xOpticalDiskDriveLetter_SetDriveLetterMulti.ps1#L27)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Thurd

Typo (funny typo ;)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/141#-:-L2ZCX3iOxB5As2hgy4i:b-hwt4pq)*

**Comment by PlagueHO** [comment]
Hi @johlju - this one is hopefully all ready to go :grin:

**Comment by johlju** [comment]
@PlagueHO Yes, I just have been busy with the day job 😞 Going through it now. 😄

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/141#-:-L2g7dX_vGKP60hnLuHI:bnfp4nl)*

**Comment by PlagueHO** [comment]
Hi @Johlju - thank you so much! I really appreciate it - and didn't mean to pester (pun intended :grin:). I do wish our day jobs wouldn't get in the way so often!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/141#-:-L2hACrNh29Q3H78wrUc:bthfi5s)*

**Comment by timhaintz** [comment]
This is awesome. Thanks @PlagueHO and @johlju . I love being able to see how much testing and reviewing goes into a release.

**Pull request merged**
