### PR TITLE
xDisk: Fixed bug not setting disk label

### PR DESCRIPTION
**Pull request by gigi81**
Fix bug #37

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xstorage/38)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xDisk/MSFT_xDisk.psm1, line 158 \[r2\]](https://reviewable.io:443/reviews/powershell/xstorage/38#-KJqZGUL4gBFNM8IUEDd:-KJqZGUL4gBFNM8IUEDe:863337984) ([raw file](https://github.com/powershell/xstorage/blob/3046337e7790c32ac5555e43a7ec6288416fb15c/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1#L158)):*
> ```PowerShell
>                 if($Volume.FileSystemLabel -ne $FSLabel)
>                 {
>                     Write-Verbose -Message "Changing volume '$($Volume.DriveLetter)' label to $FsLabel"
> ```

Should add test coverage for this scenario

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/38)*

**Comment by PlagueHO** [comment]
@gigi81 - are you able to resolve the merge conflicts on this please? Thank you! :smile:

**Comment by gigi81** [comment]
*[DSCResources/MSFT_xDisk/MSFT_xDisk.psm1, line 158 \[r2\]](https://reviewable.io:443/reviews/powershell/xstorage/38#-KJqZGUL4gBFNM8IUEDd:-KPwShWwFJvmSzCFAXgS:ba1u035) ([raw file](https://github.com/powershell/xstorage/blob/3046337e7790c32ac5555e43a7ec6288416fb15c/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1#L158)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> Should add test coverage for this scenario
</details>
test coverage added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/38)*

**Comment by gigi81** [comment]
Fixed merge conflicts and added unit tests as requested

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/38)*

**Comment by TravisEz13** [comment]
LGTM, will merge soon if there are no additional comments.

**Comment by PlagueHO** [comment]
:lgtm: Thanks for adding unit tests too :smile:

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/38#-:-KQ4pNGi9VQiBX3HccOH:bs0oimd)*

**Comment by PlagueHO** [comment]
Awesome! Thanks @TravisEz13 and @gigi81 - I'll get moving on pushing the unit test coverage on this up as far as I can.

**Pull request merged**
